### ISSUE TITLE
PEP 8 Conformity

### ISSUE THREAD

**Issue by jontayesp** [aqualid/aqualid#34]
This is not critical, but would you consider conforming to [PEP 8](https://www.python.org/dev/peps/pep-0008/)? This would make life easier for external contributors so we can all be on the same page. There are tools such as [autopep8] (https://pypi.python.org/pypi/autopep8/1.1.1) that would help with the conversion.

**Comment by menify** [comment]
Fully agree. Yes, standard is a good thing.

**Comment by menify** [comment]
Fixed all PEP8 errors in Aqualid core.
Tools still have some violations.

**Comment by jontayesp** [comment]
Awesome! Thanks.

**Comment by jknotts** [comment]
Thanks for switching to using PEP8 recommendations!

**Comment by menify** [comment]
PEP8 naming convention is not addressed yet.
For example all functions/methods are named now in camelCase style instead of lower_case.
PEP8 tool doesn't check for naming style violations, but it's still better to fix them too.

Renaming functions/methods is more risky and it would be better to do renaming by small chunks.

**Comment by jontayesp** [comment]
Ok, I'll leave this issue open for now then.

**Comment by menify** [comment]
Fixed all naming violations in Aqualid code. Tools are still not fixed. To be fixed soon.

**Comment by menify** [comment]
Fixed all PEP8 violations in all files.
